import { type Component } from "svelte";
import type Lib from "./lib/lib";
export declare function log(...args: any[]): void;
export declare function overrideKeydown(callback: (e: KeyboardEvent) => void): void;
export declare function stopOverrideKeydown(): void;
export declare function renderSvelteComponent(component: Component, props?: Record<string, any>): [HTMLDivElement, Record<string, any>];
export declare function readUserFile(accept: string): Promise<string>;
export declare const onGimkit: boolean;
export declare function parsePluginHeader(code: string): Record<string, any>;
export declare function parseLibHeader(code: string): Record<string, any>;
export default function parseHeader(code: string, headers: Record<string, any>): Record<string, any>;
export declare function confirmLibReload(libs: Lib[]): boolean;
